
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 10 20:41:51 CEST 2022
//----------------------------------------------------

package zoot.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FOIS_T = 24;
  public static final int SINON_T = 15;
  public static final int VIRGULE_T = 30;
  public static final int ECRIRE_T = 18;
  public static final int CSTENTIERE = 34;
  public static final int EQUIVAUT_T = 26;
  public static final int JUSQUA_T = 11;
  public static final int MOINS_T = 22;
  public static final int ET_T = 28;
  public static final int FONCTIONS_T = 3;
  public static final int SI_T = 13;
  public static final int OU_T = 29;
  public static final int ENTIER_T = 6;
  public static final int ALORS_T = 14;
  public static final int IDF_T = 33;
  public static final int POINTVIRGULE = 8;
  public static final int REPETER_T = 10;
  public static final int FINREPETER_T = 12;
  public static final int VARIABLES_T = 2;
  public static final int EOF = 0;
  public static final int NON_T = 21;
  public static final int DIFFERENT_T = 27;
  public static final int VRAI_T = 19;
  public static final int PLUS_T = 23;
  public static final int FINSI_T = 16;
  public static final int error = 1;
  public static final int PARENTFERME_T = 32;
  public static final int BOOLEEN_T = 7;
  public static final int RETOURNE_T = 17;
  public static final int EGAL_T = 9;
  public static final int DEBUT = 4;
  public static final int FIN = 5;
  public static final int INF_T = 25;
  public static final int FAUX_T = 20;
  public static final int PARENTOUVERT_T = 31;
}

