@startuml
package instructions {

	class Affectation extends Instruction {
		+ Affectation(LValue id, Expression exp, int noLigne, int noColonne)
		+ void verifier()
		+ String toMIPS()
	}

	Affectation --"1" LValue
	Affectation --"1" Expression

	class Ecrire extends Instruction{
		+ Ecrire (Expression exp, int ligne, int col)
		+ void verifier()
		+ String toMIPS()
	}
	Ecrire --"1" Expression

	abstract class Instruction extends ArbreAbstrait{
		# Instruction(int ligne, int colonne)
	}

	class Retourne extends Instruction implements Typed{
		+ Retourne (Expression e, int ligne, int col)
		+ void verifier()
		+ String toMIPS()
		+ Type getType()
	}
	Retourne --"1" Expression
}
@enduml