@startuml
skinparam class {
BackgroundColor AliceBlue
ArrowColor DarkTurquoise
BorderColor Turquoise
}

skinparam stereotypeCBackgroundColor DarkTurquoise
skinparam stereotypeIBackgroundColor Magenta
skinparam stereotypeABackgroundColor Yellow

hide stereotype
hide empty member

package tds {
	class Symbole {
		+ Symbole(String type)
		+ Type getType()
		+ String toString()
	}
	Symbole --"1" Type

	class SymboleVar extends Symbole {
		# int deplacement
		+ SymboleVar(String type)
		+ int getDeplacement()
	}

	class SymboleFct extends Symbole {
		# String etiquette
		+ SymboleFct(String type, String etiquette)
		+ String getEtiquette()
	}

	abstract class Entree {
		# String nom
		+ Entree(String nom)
		+ String getNom()
		+ boolean equals(Object o)
		+ int hashCode()
		+ String toString()
	}

	class EntreeVar extends Entree {
		+ EntreeVar(String nom)
	}

	class EntreeFct extends Entree {
		+ EntreeFct(String nom, String ...typeParametre)
		+ boolean equals(Object o)
		+ int hashCode()
	}
	EntreeFct --"*" String : typesParametres

	class Tds {
		- int deplacementCourant
		- Tds()
		+ static Tds getInstance()
		+ void ajouter(Entree e, Symbole s, int noLigne, int noColonne)
		+ Symbole identifier(Entree e, int noLigne, int noColonne)
		+ int getTailleZoneVariables()
		+ String toString()
		+ void reset()
	}
	Tds --"1" Tds : static
	Tds --"*" Symbole
	Tds --"*" Entree

	enum Type {
		ENTIER, BOOLEEN, NONDEFINI
	}

}

package arbre {

	package expressions {

		abstract class Constante extends Expression {
			# String cste
			# Constante(String texte, int n, int m)
			+ String toString()
		}

		class ConstanteEntiere extends Constante {
			+ ConstanteEntiere(String texte, int n, int m)
			+ String toMIPS()
			+ Type getType()
			+ String getValeur()
		}

		class ConstanteBooleene extends Constante {
			+ ConstanteBooleene(String valeur, int n, int m)
			+ String toMIPS()
			+ Type getType()
			+ String getValeur()
		}

		abstract class Expression extends ArbreAbstrait{
			# Expression(int n, int m)
			+ abstract Type getType()
			+ String getValeur()
		}

		class Idf extends Expression {
			+ Idf(Entree e, int noLigne, int noColonne)
			+ void verifier()
			+ String toMIPS()
			+ Type getType()
			+ String getNom()
			+ String toString()
			+ String getValeur()
			+ Symbole getSymbole()
		}
		Idf --"1" Symbole
		Idf --"1" Entree

		class Fonction extends Expression {
			+ Fonction(Entree e, int noLigne, int noColonne)
			+ void verifier()
			+ String toMIPS()
			+ Type getType()
			+ String getNom()
		}

		Fonction --"1" Idf : identifiant
	}
	package instructions {

		class Affectation extends Instruction {
			+ Affectation(Idf idf, Expression exp, int noLigne, int noColonne)
			+ void verifier()
			+ String toMIPS()
			+ String toString()
		}
		Affectation --"1" Idf
		Affectation --"1" Expression

		class Ecrire extends Instruction{
			+ Ecrire (Expression e, int n, int m)
			+ void verifier()
			+ String toMIPS()
			+ String toString()
		}
		Ecrire --"1" Expression

		abstract class Instruction extends ArbreAbstrait{
  	 	# Instruction(int n, int m)
		}



	}

	abstract class ArbreAbstrait {
   # int noLigne
   # int noColonne
   # ArbreAbstrait(int n, int m)
	 + int getNoLigne()
	 + int getNoColonne()
   + abstract void verifier()
   + abstract String toMIPS()
	}

	class BlocDInstructions extends ArbreAbstrait {
		# int taillePile
		+ BlocDInstructions(int n, int m)
		+ void ajouter(Instruction i)
		+ void verifier()
		+ String toMIPS()
		+ String toString()
	}
	BlocDInstructions --"*" Instruction

	class Programme extends BlocDInstructions {
		+ Programme(int n, int m)
		+ String toMIPS()
		+ void verifier()
		+ String toString()
		+ void addBlocDeFonction(BlocDeFonction b)
	}

	Programme --"*" BlocDeFonction : fonctions

	class BlocDeFonction  extends BlocDInstructions {
		+ BlocDeFonction(int n, int m)
		+ String toMIPS()
		+ String toString()
	}
}

package exceptions {
	abstract class AnalyseException extends RuntimeException {
		# AnalyseException(String m)
	}

	class AnalyseLexicaleException extends AnalyseException {
		+ AnalyseLexicaleException(int ligne, int colonne, String m)
	}

	class AnalyseSyntaxiqueException extends AnalyseException {
		+ AnalyseSyntaxiqueException(String m)
		+ AnalyseSyntaxiqueException(int ligne, int col, String m)
	}

	class AnalyseSemantiqueException extends AnalyseException{
		+ AnalyseSemantiqueException(String m)
		+ AnalyseSemantiqueException(int ligne, int col, String m)
	}

	class DoubleDeclarationException extends AnalyseSemantiqueException {
		+ DoubleDeclarationException(int ligne, int colonne, String m)
	}

	class TypeNonConcordantException extends AnalyseSemantiqueException {
		+ TypeNonConcordantException(int ligne, int colonne, String m)
	}

	class VariableNonDefinieException extends AnalyseSemantiqueException {
		+ VariableNonDefinieException(int ligne, int colonne, String m)
	}

}
@enduml