@startuml
package mips {
	class SnippetsMIPS {
	+ String enteteProgramme()
	+ String sauvegarderParametres(int positionDepart, Expression... parametres)
	+ String mettreValeurDansRegistre(String registre, String valeur)
	+ String copieRegistreVersRegistre(String registeSource, String registreDestination)
	+ String sauvegardeRegistreDansPile(String registre, int position)
	+ String sauvegardeValeurDansPile(int valeur, int position)
	+ String empilerRegistre(String registre)
	+ String restaurerRegistreDepuisPile(String registre, int position)
	+ String depilerVersRegistre(String registre)
	+ String reserverPlacePile(int nbCases)
	+ String libererPlacePile(int nbCases)
	+ String appelEcriture(Type typeAEcrire)
	+ String appelTraductionBooleen()
	+ String definitionTraductionBooleen()
	+ String sauvegardeAdresseRetourAvantAppel(int position)
	+ String restaurationAdresseRetourApresAppel(int position)
	+ String definitionRecherchePosition()
	+ String appelRecherchePosition()
	+ String additionRegistre(String resultat, String gauche, String droite)
	+ String multiplicationRegistre(String resultat, String gauche, String droite)
	}
}
@enduml