@startuml
together {
	package tds {
		together {

			class Symbole implements Typed {
				# Type type
				+ Symbole(String type)
				+ Type getType()
				+ int getNoRegion()
				+ void setNoRegion(int noRegion)
				+ void setDeplacement(int deplacement)
				+ int getDeplacement()
				+ void setEtiquette(String etiquette)
				+ String getEtiquette()
			}

			class SymboleVar extends Symbole {
				# int deplacement
				# int noRegion
				+ SymboleVar(String type)
				+ int getNoRegion()
				+ void setNoRegion(int noRegion)
				+ void setDeplacement(int deplacement)
				+ int getDeplacement()
			}

			class SymboleFct extends Symbole {
				- String etiquette
				+ SymboleFct(String type)
				+ String getEtiquette()
				+ void setEtiquette(String etiquette)
			}
		}

		together {
			abstract class Entree {
				# String nom
				+ Entree(String nom)
				+ String getNom()
				+ void setTypeParametres(String... typeParametre)
				+ boolean equals(Object o)
				+ int hashCode()
				+ abstract void declencherException(DeclencheurDException d, String message)
			}

			class EntreeVar extends Entree {
				+ EntreeVar(String nom)
				+ void declencherException(DeclencheurDException d, String message)
			}

			class EntreeFct extends Entree {
				+ EntreeFct(String nom)
				+ EntreeFct(String nom, String... typeParametres)
				+ boolean equals(Object o)
				+ void setTypeParametres(String... typeParametre)
				+ void setTypeParametres(Type... typeParametres)
				+ void declencherException(DeclencheurDException d, String message)
			}
			EntreeFct --"*" Type : typesParametres
		}

		together {
			class Tds {
				- Tds instance
				- NoeudTDS noeudCourant
				- boolean enConstruction
				- int nbNoeuds
				- Tds()
				+ static Tds getInstance()
				+ void ajouter(Entree e, Symbole s, int ligne, int colonne)
				+ Symbole identifier(Entree e, int ligne, int colonne)
				+ int getTailleZoneVar()
				+ void addVariable(Type typeVar)
				+ int getTailleZonePar()
				+ void addParametre(Type typeParam)
				+ void reset()
				+ void entreeBloc()
				+ void sortieBloc()
				+ void endConstruction()
				+ String getEtiquette(String nom)
				+ int getNoRegion()
			}
			Tds --"1" NoeudTDS : delegue
			Tds --"1" Tds : static

			class NoeudTDS {
				- int noRegion
				- int tailleZoneVar
				- int tailleZonePar
				- int noEnfantCourant
				+ NoeudTDS(int noRegion)
				+ void setParent(NoeudTDS parent)
				+ NoeudTDS getParent()
				+ void addEnfant(NoeudTDS enfant)
				+ void ajouter(Entree e, Symbole s, int noLigne, int noColonne)
				+ Symbole identifier(Entree e, int noLigne, int noColonne)
				+ int getTailleZoneVar()
				+ void addVariable(Type typeVar)
				+ int getTailleZonePar()
				+ void addParametre(Type typeParam)
				+ NoeudTDS getEnfantCourant()
				+ void enfantSuivant()
				+ void enfantPrecedent()
				+ String getEtiquette(String nom)
			}
			NoeudTDS --"*" Symbole
			NoeudTDS --"*" Entree
			NoeudTDS --"1" NoeudTDS : parent
			NoeudTDS --"*" NoeudTDS : enfants
		}

		together {
			enum Type {
				ENTIER, BOOLEEN, NONDEFINI  : faire la traduction
			}

			Interface Typed {
				+ Type getType()
			}
		}
	}
}
@enduml